const data = [
    {
        objeto: 'produto',
        id: 1,
        nome: 'Banana',
        preco: 2.00,
        secao: 'Hortifruit',
        categoria: 'fruta',
        img: "./src/img/unsplash_0WW38q7lGZA.png",
    },
    {
        objeto: 'produto',
        id: 2,
        nome: 'Morango',
        preco: 2.00,
        secao: 'Hortifruit',
        categoria: 'fruta',
        img: './src/img/unsplash_IK2ep3jMnHA.png',
    },
    {
        objeto: 'produto',
        id: 3,
        nome: 'Maçã',
        preco: 2.00,
        secao: 'Hortifruit',
        categoria: 'fruta',
        img: './src/img/unsplash_wXuzS9xR49M.png',
    },
    {
        objeto: 'produto',
        id: 4,
        nome: 'Pão',
        preco: 4.00,
        secao: 'Panificadora',
        categoria: 'Pães',
        img: './src/img/unsplash__0IzI-gEH4w.png',
    },
    {
        objeto: 'produto',
        id: 5,
        nome: 'Leite',
        preco: 5.00,
        secao: 'Laticínio',
        categoria: 'Leite',
        img: './src/img/unsplash_rbJ9BY8bRRY.png',
    },
    {
        objeto: 'produto',
        id: 6,
        nome: 'Bolo',
        preco: 6.00,
        secao: 'Panificadora',
        categoria: 'Pães',
        img: './src/img/unsplash_vdx5hPQhXFk.png',
    },
    {
        objeto: 'produto',
        id: 7,
        nome: 'Torta de Maçã',
        preco: 12.00,
        secao: 'Hortifruit',
        categoria: 'fruta',
        img: './src/img/unsplash_L1sES_uVrFI.png',
    },
    {
        objeto: 'produto',
        id: 8,
        nome: 'Yorgut Morango',
        preco: 7.00,
        secao: 'Laticínio',
        categoria: 'Leite',
        img: './src/img/unsplash_lK1Q5RyD6tc.png',
    },
]
        